[package]
authors = ["Zhenjun <netprism@netprism.org>"]
categories = ["database", "network-programming"]
description = "Backend for Zenoh using DuckDB"
edition = "2021"
license = "GPL-2.0-only"
name = "zenoh-backend-duckdb"
repository = "https://github.com/netprism/zenoh-backend-duckdb"
version = "1.5.1"
exclude = ["*.sql", "*.json"]

[lib]
name = "zenoh_backend_duckdb"
crate-type = ["cdylib", "rlib"]

[features]
default = ["dynamic_plugin", "zenoh/default"]
dynamic_plugin = []

[dependencies]
async-trait = "0.1.82"
git-version = "0.3.9"
serde_json = "1.0.128"
tokio = { version = "1.40.0", default-features = false } # Default features are disabled due to some crates' requirements
zenoh = { version = "1.5.1", default-features = false, features = [
  "internal",
  "internal_config",
  "plugins",
  "runtime_plugins",
  "unstable",
] , git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
zenoh-plugin-trait = { version = "1.5.1", git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
zenoh_backend_traits = { version = "1.5.1", git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
zenoh-ext = { version = "1.5.1", git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "main" }
zenoh-util = { version = "1.5.1", git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "main" }
duckdb = { version = "1.3.2", features = ["bundled"] }
tracing = "0.1"

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.deb]
assets = [
  ["target/release/libzenoh_backend_duckdb.so", "/usr/lib/", "644"],
  ["etc/suricata-evelog-schemas/*", "/var/zenohd/etc/suricata-evelog-schemas/", "644"],
  ["etc/init.sql", "/var/zenohd/etc/", "644"],
  ["etc/schema.version", "/var/zenohd/etc/", "644"],
  ["etc/zenohd.json5", "/var/zenohd/etc/", "644"],
  ["README.md", "/usr/share/doc/zenoh-backend-duckdb/", "644"],
  ["LICENSE", "/usr/share/doc/zenoh-backend-duckdb/", "644"],
]
copyright = "2025 NetPrism Technology"
depends = "zenoh-plugin-storage-manager (=1.5.1)"
license-file = ["LICENSE", "0"]
maintainer = "zhenjun@netprism.org"
name = "zenoh-backend-duckdb"
section = "net"
